[project]
name = "eye-saver"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "packaging>=25.0",
    "pillow>=12.0.0",
    "plyer>=2.1.0",
    "pyinstaller>=6.16.0",
    "pystray>=0.19.5",
]
